### ISSUE TITLE
docker install via get.docker.com script

### ISSUE THREAD

**Issue by chasebolt** [someara/chef-docker#520] opened 2015-10-15 00:46 UTC
i propose we move to installing docker via the get.docker.com script. the script now installs the appropriate repository for the platform and we can also add a property for enabling test/experimental builds.

**Comment by chasebolt** [comment] 2015-10-19 04:17
paging @someara, thoughts?

**Comment by someara** [comment] 2015-10-19 16:33
I think this will be trivial to implement as Yet Another Installation Method once we get the native package repo class setup. =)

**Comment by chasebolt** [comment] 2015-10-19 16:34
the get.docker.com script installs the native package repo

**Comment by someara** [comment] 2015-10-19 17:02
It sure does.

However, the other "provider" I had in my head would duplicate a lot of the
works that script does for the sake of not curl-pipe-bash'ing anything.
Also, being able to point to behind-the-firewall package mirrors is
important. We could templatize the script, but then we'd have to track
upstream anyway.

The real hurdle is figuring out the best way to enable multiple
installation methods in the docker_service resource in 12.5 world
Right now it's an exercise in subclassing and composition.

Chatting with jkeiser today about it.

-s

**Comment by chasebolt** [comment] 2015-10-19 17:09
I personally don't enjoy when the community cookbooks depend on a lot of other cookbooks because they want to support installing every installation method.

I deal with that in my wrapper cookbook to set up my private yum repos for the application and installation.

Going the curl-pipe-bash is an easy install method with no dependencies. If someone needs a more complex I'd encourage them to do it in a wrapper cookbook and set a property to disable install via curl-pipe-bash.

Of course this is just my 2 cents.

**Comment by someara** [comment] 2015-10-21 17:28
I'm going to close this for now since it is effectively a duplicate of #345 .
I promise I won't forget about it =)

**Closed by someara** 2015-10-21 17:28 UTC
