### ISSUE TITLE
uninitialized constant DockerHelpers::Container

### ISSUE THREAD

**Issue by asciifaceman** [someara/chef-docker#548] opened 2015-11-06 19:21 UTC
I am getting this fail during my usage of the docker cookbook.

```
                          [2015-11-06T11:14:25-08:00] INFO: Storing updated cookbooks/compat_resource/files/spec/data/cookbooks/test/recipes/test.rb in the cache.
                          [2015-11-06T11:14:25-08:00] INFO: Storing updated cookbooks/compat_resource/files/spec/data/config.rb in the cache.
                          [2015-11-06T11:14:25-08:00] INFO: Storing updated cookbooks/compat_resource/files/spec/data/cookbooks/test/recipes/default.rb in the cache.
                          [2015-11-06T11:14:25-08:00] INFO: Storing updated cookbooks/compat_resource/files/spec/cookbook_spec.rb in the cache.
                          [2015-11-06T11:14:25-08:00] INFO: Storing updated cookbooks/compat_resource/CHANGELOG.md in the cache.
                          [2015-11-06T11:14:25-08:00] INFO: Storing updated cookbooks/compat_resource/metadata.json in the cache.
                          [2015-11-06T11:14:25-08:00] INFO: Storing updated cookbooks/compat_resource/README.md in the cache.
                            - compat_resource
                          Compiling Cookbooks...
                          
                          ================================================================================
                          Recipe Compile Error in /var/chef/cache/cookbooks/docker/libraries/provider_docker_container.rb
                          ================================================================================
                          
                          NameError
                          ---------
                          uninitialized constant DockerHelpers::Container
                          
                          Cookbook Trace:
                          ---------------
                            /var/chef/cache/cookbooks/docker/libraries/provider_docker_container.rb:13:in `<class:DockerContainer>'
                            /var/chef/cache/cookbooks/docker/libraries/provider_docker_container.rb:9:in `<class:Provider>'
                            /var/chef/cache/cookbooks/docker/libraries/provider_docker_container.rb:8:in `<class:Chef>'
                            /var/chef/cache/cookbooks/docker/libraries/provider_docker_container.rb:7:in `<top (required)>'
                          
                          Relevant File Content:
                          ----------------------
                          /var/chef/cache/cookbooks/docker/libraries/provider_docker_container.rb:
                          
                            6:  
                            7:  class Chef
                            8:    class Provider
                            9:      class DockerContainer < Chef::Provider::LWRPBase
                           10:        # register with the resource resolution system
                           11:        provides :docker_container if Chef::Provider.respond_to?(:provides)
                           12:  
                           13>>       include DockerHelpers::Container
                           14:        include DockerHelpers::Connection
                           15:        use_inline_resources
                           16:  
                           17:        def initialize(*args)
                           18:          super
                           19:          @conn = Docker::Connection.new(parsed_connect_host, parsed_connect_options)
                           20:        end
                           21:  
                           22:        def load_current_resource
                          
                          
                          Running handlers:
                          [2015-11-06T11:14:26-08:00] ERROR: Running exception handlers
                          Running handlers complete
                          [2015-11-06T11:14:26-08:00] ERROR: Exception handlers complete
                          Chef Client failed. 0 resources updated in 11.96879567 seconds
```
I am using docker_image and docker_container. If you need to see them I can cleanse them of any secure information and post it up. I honestly can't tell what is going on, `cookbooks/docker/libraries/helpers_container.rb` is definitely there.

**Comment by asciifaceman** [comment] 2015-11-06 22:00
version: docker@2.2.4

**Comment by someara** [comment] 2015-11-07 15:48
what chef-client and compat_resource versions?

**Comment by asciifaceman** [comment] 2015-11-09 18:05
compat_resource   12.5.9
$ chef-client -v
Chef: 12.5.1

**Comment by someara** [comment] 2015-11-09 19:01
I was unable to reproduce this... my Berksfile.lock had 12.5.10.
There have been a bunch of recent fixes to compat_resource lately, so I'm %99.999 sure that's the problem here.

I've updated the metadata to depend on the compat_resource >= 12.5.14. 
Released as 2.2.5

Closing for now. Please re-open if this persists.

-s

**Closed by someara** 2015-11-09 19:01 UTC

**Comment by asciifaceman** [comment] 2015-11-09 19:13
Updated compat_resource to 12.5.14 (deleting old version), Issue persisted.
Updated chef-docker to 2.2.5, issue recovered and did not persist.
What? I thought you only changed the depends. I guess it doesn't matter as
long as it works. Thank you.

On Mon, Nov 9, 2015 at 11:01 AM, Sean OMeara <notifications@github.com>
wrote:

> Closed #548 <https://github.com/someara/chef-docker/issues/548>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/someara/chef-docker/issues/548#event-459203637>.
>



-- 
Charles P. Corbett

**Comment by gsaslis** [comment] 2015-12-06 00:22
ran into the same problem with latest version 2.3.1 and chef-client 12.5.1, chef-compat 12.5.14... 
also tried using 2.2.5 of this cookbook that @asciifaceman reported to work, but there was probably some other change that caused this to be fixed it... any ideas?

**Comment by someara** [comment] 2015-12-06 01:29
The stack trace from above is from the 1.0.x series... try deleting your chef-client cache?
-s

**Comment by gsaslis** [comment] 2015-12-06 09:22
Thanks @someara -- that was, indeed, the case... for some reason cache hadn't been updated with latest version of the docker cookbook... oh well..  :)  :+1:

**Comment by someara** [comment] 2015-12-07 17:00
This looks familiar and smells like a bug somewhere in chef-client or chef-server... can you list your platform / version information here for reference?

**Comment by gsaslis** [comment] 2015-12-08 05:56
sure @someara - this was on an ubuntu trusty (14.04), and i was just using chef-solo for the run (no chef-server involved ;) )

**Comment by CVTJNII** [comment] 2016-03-11 17:03
I'm seeing this with the following versions:

- docker cookbook: 2.5.8
- compat_resource cookbook: 12.7.3
- chef-client: 12.7.2
- chef-server: 11.1.7-1

Even though I wouldn't expect the server to cause this kind of error, that appears to be the differentiating factor between my prod and test environments.  Commenting mostly for documentation in case others have an older Chef server for legacy reasons but are trying to run current cookbooks and clients against it.

**Comment by pmahoney** [comment] 2016-05-01 04:27
I'm also seeing this issue with:

* docker 2.6.8
* compat_resource: 12.9.1
* chef-client: 12.9.38
* chef-server: 12.4.1

And I am unable to reproduce in Test Kitchen with:

* docker 2.6.8
* compat_resource: 12.9.1
* chef-client: 12.9.38
* chef-zero provisioner

It seems the server at 12.4 (prior to the 12.5 that doesn't need `compat_resource`) must be the one generating the `/var/chef/cache/cookbooks/docker/libraries/provider_docker_container.rb` file (this file is not present on the Test Kitchen instance, where there is no old Chef Server involved). Is `compat_resource` generating a bad file?  Am I not supposed to use an older Chef Server with newer clients? I'm not too familiar with all the moving parts here...

For reference, `libraries/provider_docker_container.rb` contains:

```
class Chef
  class Provider
    class DockerContainer < Chef::Provider::LWRPBase
      ...
      include DockerHelpers::Container
```

and `libraries/helpers_container.rb` contains:

```
module DockerCookbook
  module DockerHelpers
    module Container
```

so it's not surprising the error is `NameError: uninitialized constant DockerHelpers::Container`.

## Workaround

Indeed, if I add the following line to the bottom or `libraries/helpers_container.rb`, editing directly in `/var/chef/cache/cookbooks` on one of my nodes that is connected to the Chef Server 12.4:

```
DockerHelpers = DockerCookbook::DockerHelpers
```

and then run `chef-client --no-sync-cookbooks`, I do not get the error.

I'm not sure how to make this workaround more permanent however.

**Comment by chasebolt** [comment] 2016-05-01 05:53
Looks like you are running an old cookbook. Try deleting your chef cache
folder on that node.

**Comment by pmahoney** [comment] 2016-05-01 12:31
@chasebolt These version numbers come from looking in `/var/chef/cache/cookbooks`.

Hm, I'd been assuming `libraries/provider_docker_container.rb` was generated by `compat_resource`, but perhaps the answer is just that my Chef Server is serving up the wrong `docker` cookbook with the `2.6.8` metadata... Not sure how that could have happened, but won't be able to check until later.

**Comment by chasebolt** [comment] 2016-05-01 20:56
I've seen a few times where files are updated in the cache but old unused
files aren't removed. compat_resource doesn't not generate files. Removing
the cache should fix your issue and force chef to download a new copy of
the cookbook

**Comment by pmahoney** [comment] 2016-05-02 15:26
@chasebolt Deleting the entire `/var/chef/cache/cookbooks` and re-running `chef-client` results in the same behavior.  I even manually `knife cookbook upload` the docker cookbook 2.6.7 (a version that was not previously present on that Chef Server), modified my recipe to require that version, then `chef-client` fails again with the same error.  Any hints on where that `libraries/provider_docker_container.rb` file could be coming from? It is not in my local copy of the docker cookbook that I uploaded to the server.

**Comment by chasebolt** [comment] 2016-05-02 15:31
No idea how you are pulling it. That file is before v2.x iirc. When this cookbook used to be LWRP style versus the new Resource style. 

The only other suggestion I can think of is deleting all versions of the cookbook from your chef server and uploading the latest one again.

**Comment by pmahoney** [comment] 2016-05-02 15:37
@chasebolt Figured it out. I'm an idiot. Was uploading like this:

```
knife cookbook upload -o "$HOME/.berkshelf/cookbooks" docker
WARNING: * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
WARNING: The cookbooks: docker, docker exist in multiple places in your cookbook_path.
A composite version of these cookbooks has been compiled for uploading.
```

The key of course is that message **A composite version of these cookbooks has been compiled for uploading.**, and the `libraries/provider_*` files are simply from an older version that happened to be in my berkshelf.

I learned `berks upload` is the better way to do this.

**Comment by chasebolt** [comment] 2016-05-02 15:47
Haha what a bugger! Glad you figured it out 👍

**Comment by JustGav** [comment] 2016-07-03 08:29
Hi,

I'm seeing the same issue as mentioned here

Running handlers:
[2016-07-03T08:27:12+00:00] ERROR: Running exception handlers
Running handlers complete
[2016-07-03T08:27:12+00:00] ERROR: Exception handlers complete
Chef Client failed. 0 resources updated in 13 seconds
[2016-07-03T08:27:12+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2016-07-03T08:27:12+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2016-07-03T08:27:12+00:00] ERROR: uninitialized constant DockerCookbook::DockerContainer::Docker
[2016-07-03T08:27:12+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

Running docker 2.9.2
compat_resource 12.10.6

On ubuntu 16.04

**Comment by chasebolt** [comment] 2016-07-03 15:08
Did you try deleting your /var/chef/cache?

**Comment by JustGav** [comment] 2016-07-03 17:17
Yup, I tried that, both the /var/chef/cache and originally the /var/chef/cache/cookbooks

**Comment by chasebolt** [comment] 2016-07-04 05:59
Can you replicate it with test kitchen? The current test kitchen tests
pass.

**Comment by mburns** [comment] 2016-10-20 22:21
For what it is worth, I ran into a similar error (`uninitialized constant Docker::Network`) when both `docker` and `docker-api` gems were installed, because they both use a common namespace. If the gems are loaded in the wrong order, things get wony.

**Comment by trinitronx** [comment] 2020-07-20 03:31
> 
> I learned `berks upload` is the better way to do this.

Just ran into this on Ubuntu `20.04` / Focal Fossa, Chef Infra Client: `16.2.73` & `docker` cookbook version `6.0.3`.  Couldn't reproduce in CI / CD or any local testing.  Same thing fixed it:  `berks upload`

Originally I'd tried to just use `knife cookbook upload  my-docker-wrapper --include-dependencies`.  `chef-client` threw a similar error, but with `libraries/provider_docker_service.rb`.  Must've been some old cookbook hanging around on hosted chef server.
